#!/bin/bash
set -euo pipefail
myip=$(myip)
sgid="$(aws ec2 describe-security-groups --group-names "cewong builder security group" | jq -r '.SecurityGroups[0].GroupId')"
sgruleid="$(aws ec2 describe-security-group-rules --filters Name=group-id,Values=${sgid} | jq -r '.SecurityGroupRules[] | select(.IsEgress == false) | .SecurityGroupRuleId')"
aws ec2 modify-security-group-rules --group-id ${sgid} --security-group-rules "SecurityGroupRuleId=${sgruleid},SecurityGroupRule={CidrIpv4=${myip}/32,IpProtocol=tcp,FromPort=22,ToPort=22}" > /dev/null
